version: "3.8"

services:
  mongo:
    image: oanliju/mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  springboot-app:
    image: oanliju/springboot-app:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/testdb
    depends_on:
      mongo:
        condition: service_healthy

  flask-service:
    image: oanliju/flask-service:latest
    container_name: flask-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/image_db
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
