name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Spring Boot ---
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Maven Wrapper executable
        run: chmod +x ./imageupload/mvnw

      - name: Build Spring Boot JAR
        run: ./mvnw clean package -DskipTests
        working-directory: ./imageupload

      # --- Docker Build ---
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest ./imageupload
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-service:latest ./flask-image-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mongo:6 ./mongo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mongo:6

      # --- Déploiement sur AWS EC2 ---
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            
            # Arrêt et suppression des anciens conteneurs
            docker compose -f docker-compose.yml down
            
            # Démarrage des conteneurs avec Compose
            docker compose -f docker-compose.yml up -d
